### ISSUE TITLE
Provide support for services 

### ISSUE THREAD

**Issue by francocipollone** [osrf/rmw_zenoh#80]
### Tasks
- [ ] Implement service side rmw methods
- [ ] Implement client side rmw methods
- [ ] Update graph cache accordingly
- [ ] Implement methods related to services introspection

**Comment by francocipollone** [comment]
Some wip at https://github.com/ros2/rmw_zenoh/compare/rolling...francocipollone/service_support_via_queryable via using zenoh queryable.

It might change to use topics as the DDS-based implementations due to rmw api current behavior. Being discussed.

**Comment by francocipollone** [comment]
Some comment related to zenoh queryables and ownerships:

### Context

Following RMW implementation if using queryable:
- The queryable is declared at rmw_create_service
- A query is analized at rmw_take_request
- A query is answered at rmw_send_response

### Issue

In this example: https://github.com/eclipse-zenoh/zenoh-c/blob/master/examples/z_queryable.c#L28-L42

The callback for the queryable receives a z_query_t pointer. 
The method that is used to send a reply is: z_query_reply (For what I saw from docstrings: "This function must be called inside of a Queryable callback passing the
query received as parameters of the callback function" )

After double checking with Zettascale folks: using the z_query_t outside of its callback is UB, as said query is destroyed. It is in the roadmap to support this API.

### Alternative
We could move forward using publishers and subscriptions for service support, typically how it is done for the dds-based implementations, and upgrade to use Queryables later on when supported.

**Comment by clalancette** [comment]
> We could move forward using publishers and subscriptions for service support, typically how it is done for the dds-based implementations, and upgrade to use Queryables later on when supported.

I don't love the 2 topic solution (it leads to races), but this is an OK workaround for now.  Once we get the queryable-handle support later, we can switch to it.

The only thing I'll suggest is that we design the API so that we can easily switch to the queryable-based solution in the future.

**Comment by JEnoch** [comment]
> It is in the roadmap to support this API.

Actually owned queries are coming very soon in zenoh-c: https://github.com/eclipse-zenoh/zenoh-c/pull/213
And will come later for zenoh-pico.

**Comment by francocipollone** [comment]
> > It is in the roadmap to support this API.
> 
> Actually owned queries are coming very soon in zenoh-c: [eclipse-zenoh/zenoh-c#213](https://github.com/eclipse-zenoh/zenoh-c/pull/213) And will come later for zenoh-pico.

Awesome, thanks for tackling this quickly

**Comment by nkoenig** [comment]
@Yadunund and @francocipollone , checking to see if services are now supported? I see #86 and #88, both of which seem promising.

**Comment by clalancette** [comment]
> @Yadunund and @francocipollone , checking to see if services are now supported? I see #86 and #88, both of which seem promising.

Sort of.  They work in their most basic form, but they are pretty buggy right now.  #90 adds in graph introspection for services.  I'm working on some additional fixes on top of #90 which improves the reliability of them.  Hopefully after that they will be closer to "done".

**Comment by clalancette** [comment]
We've fixed all of the known issues with services right now, so closing this.  Any other problems we can ticket separately.
